package com.alphadragon.pos.security

import android.content.Context
import android.security.keystore.KeyGenParameterSpec
import android.security.keystore.KeyProperties
import android.util.Base64
import com.alphadragon.core.common.AppConfig
import com.alphadragon.core.common.Logger
import dagger.hilt.android.qualifiers.ApplicationContext
import java.security.KeyStore
import java.security.SecureRandom
import javax.crypto.Cipher
import javax.crypto.KeyGenerator
import javax.crypto.SecretKey
import javax.crypto.spec.GCMParameterSpec
import javax.inject.Inject
import javax.inject.Singleton

/**
 * Android Keystore wrapper. All sensitive key material is stored here.
 * Keys are hardware-backed on devices with a secure element.
 *
 * Hardware-backed SecretKey.encoded returns null — we must use AES-GCM
 * to wrap/unwrap passphrases rather than accessing raw key bytes directly.
 */
@Singleton
class KeystoreManager @Inject constructor(
    @ApplicationContext private val context: Context
) {
    private val keyStore: KeyStore by lazy {
        KeyStore.getInstance(AppConfig.KEYSTORE_PROVIDER).apply { load(null) }
    }

    private val prefs by lazy {
        context.getSharedPreferences("keystore_wrapped", Context.MODE_PRIVATE)
    }

    private companion object {
        const val GCM_TAG_LENGTH = 128
        const val GCM_IV_LENGTH = 12
        const val PASSPHRASE_LENGTH = 32
        const val DB_PASSPHRASE_PREF = "db_pass"
    }

    /**
     * Returns the 32-byte SQLCipher passphrase for the database.
     * On first call: generates a random passphrase, encrypts it with the Keystore AES key,
     * and stores the ciphertext in SharedPreferences.
     * On subsequent calls: retrieves and decrypts the stored ciphertext.
     *
     * Hardware-backed keys cannot expose raw bytes, so we use the key for AES-GCM
     * encrypt/decrypt rather than reading key.encoded.
     */
    fun getOrCreateDbPassphrase(): ByteArray {
        val stored = prefs.getString(DB_PASSPHRASE_PREF, null)
        val dbKeyAlias = AppConfig.DB_KEY_ALIAS

        ensureKeyExists(dbKeyAlias)

        return if (stored != null) {
            try {
                val ciphertext = Base64.decode(stored, Base64.DEFAULT)
                decrypt(dbKeyAlias, ciphertext)
            } catch (e: Exception) {
                Logger.e("Failed to decrypt db passphrase — regenerating", e, "KeystoreManager")
                generateAndStorePassphrase(dbKeyAlias)
            }
        } else {
            generateAndStorePassphrase(dbKeyAlias)
        }
    }

    /** Store a merchant API key (raw bytes) encrypted under a per-merchant Keystore key. */
    fun storeApiKey(alias: String, keyBytes: ByteArray) {
        ensureKeyExists(alias)
        val ciphertext = encrypt(alias, keyBytes)
        prefs.edit()
            .putString("apikey_$alias", Base64.encodeToString(ciphertext, Base64.DEFAULT))
            .apply()
    }

    /** Retrieve a merchant API key. Returns null if not stored. */
    fun getApiKey(alias: String): ByteArray? {
        val stored = prefs.getString("apikey_$alias", null) ?: return null
        return runCatching {
            decrypt(alias, Base64.decode(stored, Base64.DEFAULT))
        }.getOrNull()
    }

    fun deleteKey(alias: String) {
        runCatching {
            if (keyStore.containsAlias(alias)) keyStore.deleteEntry(alias)
            prefs.edit().remove("apikey_$alias").apply()
        }.onFailure { Logger.e("Failed to delete key: $alias", it, "KeystoreManager") }
    }

    fun containsKey(alias: String): Boolean =
        runCatching { keyStore.containsAlias(alias) }.getOrDefault(false)

    // ── Internal helpers ──────────────────────────────────────────────────────

    private fun ensureKeyExists(alias: String) {
        if (!keyStore.containsAlias(alias)) generateAesKey(alias)
    }

    private fun generateAndStorePassphrase(alias: String): ByteArray {
        val passphrase = ByteArray(PASSPHRASE_LENGTH).also { SecureRandom().nextBytes(it) }
        val ciphertext = encrypt(alias, passphrase)
        prefs.edit()
            .putString(DB_PASSPHRASE_PREF, Base64.encodeToString(ciphertext, Base64.DEFAULT))
            .apply()
        return passphrase
    }

    /**
     * AES-GCM encrypt. Returns IV (12 bytes) + ciphertext concatenated.
     */
    private fun encrypt(alias: String, plaintext: ByteArray): ByteArray {
        val key = getSecretKey(alias) ?: generateAesKey(alias)
        val cipher = Cipher.getInstance("AES/GCM/NoPadding")
        cipher.init(Cipher.ENCRYPT_MODE, key)
        val iv = cipher.iv  // 12-byte IV generated by the cipher
        val encrypted = cipher.doFinal(plaintext)
        return iv + encrypted
    }

    /**
     * AES-GCM decrypt. Expects IV (12 bytes) + ciphertext.
     */
    private fun decrypt(alias: String, ivPlusCiphertext: ByteArray): ByteArray {
        val key = requireNotNull(getSecretKey(alias)) { "Keystore key '$alias' missing for decryption" }
        val iv = ivPlusCiphertext.copyOfRange(0, GCM_IV_LENGTH)
        val ciphertext = ivPlusCiphertext.copyOfRange(GCM_IV_LENGTH, ivPlusCiphertext.size)
        val cipher = Cipher.getInstance("AES/GCM/NoPadding")
        cipher.init(Cipher.DECRYPT_MODE, key, GCMParameterSpec(GCM_TAG_LENGTH, iv))
        return cipher.doFinal(ciphertext)
    }

    private fun getSecretKey(alias: String): SecretKey? =
        runCatching {
            (keyStore.getEntry(alias, null) as? KeyStore.SecretKeyEntry)?.secretKey
        }.getOrNull()

    private fun generateAesKey(alias: String): SecretKey {
        val keyGenerator = KeyGenerator.getInstance(
            KeyProperties.KEY_ALGORITHM_AES,
            AppConfig.KEYSTORE_PROVIDER
        )
        keyGenerator.init(
            KeyGenParameterSpec.Builder(
                alias,
                KeyProperties.PURPOSE_ENCRYPT or KeyProperties.PURPOSE_DECRYPT
            )
                .setBlockModes(KeyProperties.BLOCK_MODE_GCM)
                .setEncryptionPaddings(KeyProperties.ENCRYPTION_PADDING_NONE)
                .setKeySize(256)
                .setUserAuthenticationRequired(false)
                .build()
        )
        return keyGenerator.generateKey()
    }
}
